// Core types for the ArtMatch app

export interface Artwork {
  id: string
  title: string
  artist: string
  price: number
  style: string
  medium: string
  dimensions: {
    width: number
    height: number
    depth?: number
    unit: 'inches' | 'cm'
  }
  image_url: string
  gallery_id: string
  description: string
  year_created: number
  availability_status: 'available' | 'sold' | 'reserved'
  explanation?: string  // Why you might like this - generated by recommendation engine
}

export interface Gallery {
  id: string
  name: string
  address: string
  latitude: number
  longitude: number
  contact: {
    phone?: string
    email?: string
    website?: string
  }
  description: string
  opening_hours: string
  verified: boolean
}

export interface User {
  id: string
  username: string
  budget_min: number
  budget_max: number
  preferences: {
    styles: Record<string, number>
    budget_range: [number, number]
  }
  onboarding_completed: boolean
  created_at: string
}

export interface Swipe {
  user_id: string
  artwork_id: string
  action: 'like' | 'pass'
  timestamp: string
}

export interface Collection {
  id: string
  user_id: string
  name: string
  description: string
  created_at: string
}

export interface CollectionItem {
  collection_id: string
  artwork_id: string
  added_at: string
  notes?: string
}

export type RootStackParamList = {
  Onboarding: undefined
  Main: undefined
  ArtworkDetail: { artworkId: string }
  ARPreview: { artworkId: string }
  GalleryProfile: { galleryId: string }
  ArtistProfile: { artistName: string }
}
